### ISSUE TITLE
Nested loader doesn't work

### ISSUE THREAD

**Issue by mtsmfm** [Shopify/graphql-batch#144]
It seems `fulfill(key, Loader.load)` is tested 

https://github.com/Shopify/graphql-batch/blob/211b11a516f526e675dec78fbbd8aeac1d18d8e1/test/loader_test.rb#L32

But actually it doesn't work:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'graphql', '1.12.17'
  gem 'graphql-batch', '0.4.3'
end

class NestedLoader < GraphQL::Batch::Loader
  def perform(keys)
    keys.each { |key| fulfill(key, EchoLoader.load(key)) }
  end
end

class EchoLoader < GraphQL::Batch::Loader
  def perform(keys)
    keys.each { |key| fulfill(key, key) }
  end
end

class QueryType < GraphQL::Schema::Object
  field :test, String, null: false

  def test
    NestedLoader.load('test')
  end
end

class AppSchema < GraphQL::Schema
  query QueryType
  use GraphQL::Batch
end

p AppSchema.execute(<<~Q).to_h
query {
  test
}
Q
```

```
Traceback (most recent call last):
        53: from foo.rb:36:in `<main>'
        52: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/schema.rb:1659:in `execute'
        51: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/schema.rb:1688:in `multiplex'
        50: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:50:in `run_all'
        49: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:60:in `run_queries'
        48: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/tracing.rb:66:in `trace'
        47: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
        46: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
        45: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
        44: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        43: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
        42: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
        41: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        40: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
        39: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
        38: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
        37: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
        36: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'
        35: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
        34: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:110:in `run_as_multiplex'
        33: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
        32: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:111:in `block in run_as_multiplex'
        31: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter.rb:54:in `finish_multiplex'
        30: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter.rb:93:in `sync_lazies'
        29: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/tracing.rb:66:in `trace'
        28: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter.rb:94:in `block in sync_lazies'
        27: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter/resolve.rb:10:in `resolve_all'
        26: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
        25: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter/resolve.rb:10:in `block in resolve_all'
        24: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter/resolve.rb:47:in `resolve'
        23: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/lazy.rb:41:in `value'
        22: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:864:in `block in after_lazy'
        21: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/query.rb:365:in `with_error_handling'
        20: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/errors.rb:107:in `with_error_handling'
        19: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/query.rb:366:in `block in with_error_handling'
        18: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:866:in `block (2 levels) in after_lazy'
        17: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/tracing.rb:66:in `trace'
        16: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:867:in `block (3 levels) in after_lazy'
        15: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/schema.rb:127:in `sync_lazy'
        14: from /usr/local/bundle/gems/graphql-1.12.17/lib/graphql/schema.rb:127:in `public_send'
        13: from /usr/local/bundle/gems/promise.rb-0.7.4/lib/promise.rb:80:in `sync'
        12: from /usr/local/bundle/gems/promise.rb-0.7.4/lib/promise.rb:129:in `wait'
        11: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:71:in `wait'
        10: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/executor.rb:51:in `resolve'
         9: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:63:in `resolve'
         8: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:142:in `check_for_broken_promises'
         7: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:142:in `each'
         6: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:145:in `block in check_for_broken_promises'
         5: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:91:in `reject'
         4: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:116:in `finish_resolve'
         3: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/executor.rb:81:in `around_promise_callbacks'
         2: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:117:in `block in finish_resolve'
         1: from /usr/local/bundle/gems/graphql-batch-0.4.3/lib/graphql/batch/loader.rb:92:in `block in reject'
/usr/local/bundle/gems/promise.rb-0.7.4/lib/promise.rb:117:in `reject': NestedLoader didn't fulfill promise for key "test" (Promise::BrokenError)
```

Is this intentional?

**Comment by mtsmfm** [comment]
It seems it's fixed by 0.5.0
