### ISSUE TITLE
Issues with graphql-relay 0.9.5 and graphql 0.13

### ISSUE THREAD

**Issue by andrewfader** [Shopify/graphql-batch#9]
Looks like the interface for connections has changed somehow

```
NoMethodError - undefined method `offset' for #<Team:0x00000007fc2d60>:
  activemodel (4.2.6) lib/active_model/attribute_methods.rb:433:in `method_missing'
  graphql-relay (0.9.5) lib/graphql/relay/relation_connection.rb:32:in `sliced_nodes'
  graphql-relay (0.9.5) lib/graphql/relay/relation_connection.rb:23:in `paged_nodes'
  graphql-relay (0.9.5) lib/graphql/relay/relation_connection.rb:82:in `paged_nodes_array'
  graphql-relay (0.9.5) lib/graphql/relay/relation_connection.rb:5:in `cursor_from_node'
  graphql-relay (0.9.5) lib/graphql/relay/edge.rb:14:in `cursor'
  graphql (0.13.0) lib/graphql/field.rb:111:in `block in build_default_resolver'
  graphql (0.13.0) lib/graphql/field.rb:67:in `resolve'
  graphql (0.13.0) lib/graphql/query/serial_execution/field_resolution.rb:69:in `block in get_middleware_proc_from_field_resolve'
  graphql (0.13.0) lib/graphql/schema/middleware_chain.rb:24:in `call'
  graphql (0.13.0) lib/graphql/schema/rescue_middleware.rb:34:in `call'
  graphql (0.13.0) lib/graphql/schema/middleware_chain.rb:24:in `call'
  graphql (0.13.0) lib/graphql/query/serial_execution/field_resolution.rb:58:in `get_raw_value'
  graphql (0.13.0) lib/graphql/query/serial_execution/field_resolution.rb:26:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:98:in `resolve_field'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:18:in `block in result'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:17:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/value_resolution.rb:72:in `non_null_result'
  graphql (0.13.0) lib/graphql/query/serial_execution/value_resolution.rb:23:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/field_resolution.rb:45:in `get_finished_value'
   () home/andrew/bundle/ruby/2.3.0/bundler/gems/graphql-batch-9cf8341196a8/lib/graphql/batch/execution_strategy.rb:56:in `get_finished_value'
  graphql (0.13.0) lib/graphql/query/serial_execution/field_resolution.rb:30:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:98:in `resolve_field'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:18:in `block in result'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:17:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/value_resolution.rb:72:in `non_null_result'
  graphql (0.13.0) lib/graphql/query/serial_execution/value_resolution.rb:23:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/field_resolution.rb:45:in `get_finished_value'
   () home/andrew/bundle/ruby/2.3.0/bundler/gems/graphql-batch-9cf8341196a8/lib/graphql/batch/execution_strategy.rb:56:in `get_finished_value'
  graphql (0.13.0) lib/graphql/query/serial_execution/field_resolution.rb:30:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:98:in `resolve_field'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:18:in `block in result'
  graphql (0.13.0) lib/graphql/query/serial_execution/selection_resolution.rb:17:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution/operation_resolution.rb:20:in `result'
  graphql (0.13.0) lib/graphql/query/serial_execution.rb:17:in `execute'
   () home/andrew/bundle/ruby/2.3.0/bundler/gems/graphql-batch-9cf8341196a8/lib/graphql/batch/execution_strategy.rb:4:in `execute'
  graphql (0.13.0) lib/graphql/query/executor.rb:38:in `execute'
  graphql (0.13.0) lib/graphql/query/executor.rb:15:in `result'
  graphql (0.13.0) lib/graphql/query.rb:47:in `result'
  graphql (0.13.0) lib/graphql/schema.rb:55:in `execute'
  app/controllers/api/v1/graph_ql_controller.rb:14:in `execute'

```

**Comment by dylanahsmith** [comment]
graphql-batch is in no way related to graphql-relay and we aren't experiencing any problems when using it with graphql gem version 0.13.  Please provide steps to reproduce your problem rather than just a backtrace that references your application code.

**Comment by rmosolgo** [comment]
Sounds like: https://github.com/rmosolgo/graphql-relay-ruby/issues/38

**Comment by andrewfader** [comment]
Whoops. Thanks
